/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AqHPTTPvD5r
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
} from "@/components/ui/dropdown-menu";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import { Dialog, DialogTrigger, DialogContent } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { JSX, SVGProps } from "react";

export function DashBoard() {
  return (
    <div className="flex flex-col min-h-screen">
      
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 p-4 sm:p-6 lg:p-8">
        
        <Card>
          <CardHeader>
            <CardTitle>Swap</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="grid grid-cols-2 gap-2">
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder="From" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="sol">Solana (SOL)</SelectItem>
                    <SelectItem value="usdc">USDC</SelectItem>
                    <SelectItem value="usdt">USDT</SelectItem>
                  </SelectContent>
                </Select>
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder="To" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="sol">Solana (SOL)</SelectItem>
                    <SelectItem value="usdc">USDC</SelectItem>
                    <SelectItem value="usdt">USDT</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-2 gap-2">
                <Input type="number" placeholder="Amount" />
                <Button className="w-full">Swap</Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
      <Dialog>
        <DialogTrigger asChild>
          <Card className="w-full max-w-md cursor-pointer">
            <CardHeader>
              <CardTitle>Transaction #123456</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2">
                <Avatar className="w-10 h-10">
                  <AvatarImage
                    src="/placeholder-user.jpg"
                    alt="Recipient Avatar"
                  />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">John Doe</div>
                  <div className="text-muted-foreground">john@example.com</div>
                </div>
                <div className="ml-auto text-right">
                  <div className="font-medium">$50.00</div>
                  <div className="text-muted-foreground">2023-04-15</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[600px]">
          <div className="flex flex-col h-[600px]">
            <div className="border-b p-4 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Avatar className="w-10 h-10">
                  <AvatarImage
                    src="/placeholder-user.jpg"
                    alt="Recipient Avatar"
                  />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">John Doe</div>
                  <div className="text-muted-foreground">john@example.com</div>
                </div>
              </div>
              <div className="text-right">
                <div className="font-medium">$50.00</div>
                <div className="text-muted-foreground">2023-04-15</div>
              </div>
            </div>
            <ScrollArea className="flex-1 p-4">
              <div className="grid gap-4">
                <div className="flex items-start gap-2">
                  <Avatar className="w-8 h-8">
                    <AvatarImage
                      src="/placeholder-user.jpg"
                      alt="User Avatar"
                    />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div className="bg-muted rounded-lg p-2 max-w-[80%]">
                    <div className="font-medium">John Doe</div>
                    <div>
                      Hey, I'd like to send you $50 for the product. Can you
                      confirm the details?
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-2 justify-end">
                  <div className="bg-primary rounded-lg p-2 text-primary-foreground max-w-[80%]">
                    <div className="font-medium">You</div>
                    <div>
                      Sure, the details are all correct. I'll send the product
                      right away.
                    </div>
                  </div>
                  <Avatar className="w-8 h-8">
                    <AvatarImage
                      src="/placeholder-user.jpg"
                      alt="User Avatar"
                    />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                </div>
                <div className="flex items-start gap-2">
                  <Avatar className="w-8 h-8">
                    <AvatarImage
                      src="/placeholder-user.jpg"
                      alt="User Avatar"
                    />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div className="bg-muted rounded-lg p-2 max-w-[80%]">
                    <div className="font-medium">John Doe</div>
                    <div>
                      Great, thanks! I'll be on the lookout for the package.
                    </div>
                  </div>
                </div>
              </div>
            </ScrollArea>
            <div className="border-t p-4">
              <Input
                type="text"
                placeholder="Type your message..."
                className="w-full rounded-md pr-12"
              />
              <Button
                variant="ghost"
                size="icon"
                className="absolute right-4 top-1/2 -translate-y-1/2"
              >
                <SendIcon className="w-5 h-5" />
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}



function SearchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function SendIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  );
}

